### ISSUE TITLE
Autoraise does not function if a system notification is present

### ISSUE THREAD

**Issue by strowger** [synappser/AutoFocus#10]
**Describe the bug**
Autoraise does not function if a system notification is present

**To Reproduce**
1. Open some application windows
2. Generate a standard OSX system notification (for example, by sending yourself an email using your iphone while you have mail.app open)
3. Attempt to autoraise some windows by mouseing-over them while the notificaiton is present
4. See that windows do not raise
5. Retry once notification has gone and see that windows do raise

**Expected behavior**
Windows should auto-raise even if a notification is present.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 12.5
 - CPU: M1 Max, M2
 - Version: v0.6.2b

**Comment by synappser** [comment]
Bug confirmed. Thank you. Indeed a notification such as `osascript -e 'display notification "hello world!"'` prevents windows focus when it shouldn't.

**Comment by synappser** [comment]
Issue fixed with release [v0.6.6b](https://github.com/synappser/AutoFocus/releases/tag/v0.6.6).
