### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by RaySimmons** [synappser/AutoFocus#13]
Hello, I can't get the program to work. Is there a setup guide? Thanks, Ray

**Comment by synappser** [comment]
Hi Ray,

You were supposed :wink: to give me more details about as your operating system version, the steps you followed, etc. Anyway, here's a link to a video with instructions on installing FinderFix but the same applies to AutoFocus. Just follow it until the end and do not forget to push the switch On:

https://synappser.github.io/images/screencasts/02-ff-video.mp4

Here's another video showing how AutoFocus works with an additional workflow at the end of the video:

https://synappser.github.io/images/screencasts/04-af-video.mp4

Keep me posted on how things go and where you are stuck.

Synappser

**Comment by synappser** [comment]
Please feel free to re-open if your issue was not answered sufficiently.
