### ISSUE TITLE
Suggested Workaround for AutoFocus Interfering with Overlay Add-Ins like Default Folder X

### ISSUE THREAD

**Issue by mikeglenn** [synappser/AutoFocus#15]
Hello. I'm really enjoying AutoFocus beta. Only one issue so far: Default Folder X is an add-in that creates a sidebar-like overlay for Open/Save dialogs to let you easily select recent folders or files. The problem is, with AutoFocus activated, the Default Folder X overlay disappears as soon as you move the cursor over it, so only the original Open/Close dialog remains visible. AutoFocus has to be disabled to allow Default Folder X to function properly. 

**Describe the solution you'd like**
If there's no easy way to prevent AutoFocus from interfering with overlays like this, an acceptable workaround might be to add an option in AutoFocus Preferences that does the **opposite** of Auto raise window under cursor: "Only allow when one of the following keys is pressed."  It could be called: "Disable AutoFocus while one of the following keys is pressed." So, for example, if someone selected this new option, they could hold down the Option key while interacting with the Default Folder X overlay to prevent it from disappearing.

**Describe alternatives you've considered**
The only other alternative I can think of is if you can figure out a way to prevent AutoFocus from interfering with these kinds of overlays. In my opinion, it would be too annoying to use AutoFocus with "Only allow when one of the following keys is pressed." enabled all the time. That would make me not want to use AutoFocus at all.

**Additional context**

- AutoFocus version 0.6.6 (1)
- macOS 13.2.1
- M2 Pro Mac mini

**Two screenshots:** (1) Standard Open/Save dialog and (2) Default Folder X overlay that normally appears around it:
<img width="800" alt="Screenshot AutoFocus Default Folder X issue 2023-03-02 at 12 37 45 PM" src="https://user-images.githubusercontent.com/6611407/222513255-b8b13143-4659-424d-89d3-c9b3a154c536.png">
<img width="915" alt="Screenshot AutoFocus Default Folder X issue  2023-03-02 at 12 32 31 PM" src="https://user-images.githubusercontent.com/6611407/222513249-f1b99500-4d76-4748-b9f9-2d6cd35689f1.png">

**Comment by synappser** [comment]
Hi @mikeglenn,

Thank you for the detailed suggestion. As the saying goes, great minds think alike 😉. Yesterday I finished the first pass on an experimental "Focus **Without** Raising" feature to be added to the next release. It comes with an option to temporarily disable it by holding the Function modifier key (fn) to get the regular window raising behaviour. It's working pretty well and I was already thinking that it would be handy to have a similar opposite key modifier on the current "Focus **With** Raising".

Another approach would be to add an exclusion list for selected applications but that would be longer to implement.

I'm adding both solutions to my todo list.

Thanks

**Comment by mikeglenn** [comment]
Wow, amazing that you were already working on this! [👏🏼]

Focus Without Raising should be a good quick fix while exclusion list sounds like the ultimate long-term solution if you have time to get around to it. Great that you’re thinking about adding both. Looking forward to testing.

Mike

From: synappser ***@***.***>
Date: Thursday, March 2, 2023 at 2:25 PM
To: synappser/AutoFocus ***@***.***>
Cc: MikeG ***@***.***>, Mention ***@***.***>
Subject: Re: [synappser/AutoFocus] Suggested Workaround for AutoFocus Interfering with Overlay Add-Ins like Default Folder X (Issue #15)

Hi @mikeglenn<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmikeglenn&data=05%7C01%7C%7C94081ac4a66b436f1aa108db1b53ddc9%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638133819239192425%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FQ1ocW8Cd0xgaNjRb6I8ss1Dz0W42j5qg2FqYjwP6lg%3D&reserved=0>,

Thank you for the detailed suggestion. As the saying goes, great minds think alike 😉. Yesterday I finished the first pass on an experimental "Focus Without Raising" feature to be added to the next release. It comes with an option to temporarily disable it by holding the Function modifier key (fn) to get the regular window raising behaviour. It's working pretty well and I was already thinking that it would be handy to have a similar opposite key modifier on the current "Focus With Raising".

Another approach would be to add an exclusion list for selected applications but that would be longer to implement.

I'm adding both solutions to my todo list.

Thanks

**Comment by synappser** [comment]
Partially implemented in v0.6.7b.

**Comment by mikeglenn** [comment]
Thanks! 🥳
