### ISSUE TITLE
Unable to use Emoji Picker

### ISSUE THREAD

**Issue by davidindub** [synappser/AutoFocus#20]
**Describe the bug**
When trying to use the emoji picker with the cursor/pointer, the picker will close as focus goes back to the main window.

**To Reproduce**
1. Use TextEdit or anywhere you can input text in another app
2. Bring up the emoji picker (globe key shortcut on most Mac)
3. Try to pick an emoji using the pointer

**Expected behavior**
You should be able to pick an emoji with the pointer

**Desktop:**
 - OS: macOS Ventura 13.4
 - CPU: Apple M1 Pro
- MacBook Pro 16-inch, 2021

- AutoFocus 0.6.6 (1)

**Comment by synappser** [comment]
Fixed in v0.6.7b.
