### ISSUE TITLE
Quits after first raise event immediately after opening app; May be related to specific configuration

### ISSUE THREAD

**Issue by RauschUndNot** [synappser/AutoFocus#24]
**Describe the bug**
AUTOFOCUS quits after the first raise event immediately after opening the app. This may be related to a specific settings configuration. This started happening after I upgraded to the latest beta after I received a message saying my current version was out-of-date. 

After I upgraded, I wanted to see if any of the functionality had changed: I selected "Invert action" and "Focus without raising window." When I attempted to hover over an unfocused window, the app quit. 

I am using the word "quit" to describe what happened, but maybe this could be considered a "crash."

**To Reproduce**
1. Open AUTOFOCUS Settings.
2. Select settings: "Invert action" and "Focus without raising window."
3. **THIS IS THE UNEXPECTED BEHAVIOR**: Move the pointer over an unfocused window; AUTOFOCUS should quit.
4. Once AUTOFOCUS has quit, relaunch AUTOFOCUS.
5. _OPTIONAL_: Open AUTOFOCUS Settings and confirm that the same configuration is set.
6. **THIS IS THE UNEXPECTED BEHAVIOR AGAIN**: Move the pointer over an unfocused window; AUTOFOCUS should quit.

**Expected behavior**
I expected AUTOFOCUS to focus to the unfocused window and not quit. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.2.1
 - CPU: Apple M2 Pro
 - Version 0.6.8 (30)

**Additional context**
Three monitors. Using Stage Manager. 

Thank you.

**Comment by synappser** [comment]
"Auto raise" and "Focus without raising" do not work together. I'll make this more obvious by disabling either one when the other is checked with the next release. For the time being, please manually un-check "Only allow when one of the following keys is pressed:" when you check "Focus without raising window". The "fn temporarily allows raising" checkbox is meant to invert this action.

Thank you for the bug report and please keep me posted.

**Comment by RauschUndNot** [comment]
Hello,

I forgot to mention: I am unable to uncheck anything because the AUTOFOCUS settings window is unfocused after it opens. Once I move the pointer to the window, it closes since AUTOFOCUS quits.

**Comment by RauschUndNot** [comment]
I was so focused on writing this post and the comment that I forgot that say: Thank you for your app. It is very helpful.

**Comment by synappser** [comment]
You're welcome @RauschUndNot.

AutoFocus is getting contradictory orders from its preferences plist file, so you need to reset it first.

Delete com.mantel.AutoFocus.plist from /Users/your_name/Library/Preferences/ folder.

If that's not enough, click Go > Go to Folder... in Finder's menu bar. Enter /private/var/folders/_d/ in the dialog box field and press Return.

Then open the folder with the cryptic long name (e.g. v4l5....). There you will find, among others, a folder named "C". Open it and delete the folder named "com.mantel.AutoFocus".

You should now be able to cleanly restart AutoFocus and change your settings.

**Comment by RauschUndNot** [comment]
Hello,

I tried all of the above but none of it worked. But it seems that restarting the computer did the trick, so I am closing this issue. Thank you.
