### ISSUE TITLE
Allow FFM without Autoraise

### ISSUE THREAD

**Issue by benAKdodson** [synappser/AutoFocus#6]
**Is your feature request related to a problem? Please describe.**
The main reason I use an Autoraise program is for focus to follow mouse, without windows being raised. I have a homebrew app that has this functionality - but it behaves very poorly with Control Centre. So when I saw your app I decided to give it a shot.
It works perfectly but is sorely missing the option to auto focus without raising.

**Describe the solution you'd like**
An option to just autofocus, without raise

**Comment by synappser** [comment]
> It works perfectly

Thank you, I really appreciate the compliment.

The good news is you're not the first user to request this feature (see https://github.com/synappser/AutoRaise/issues/3), so it's on my radar. Stay tuned.

**Comment by synappser** [comment]
Implemented in v0.6.7b.
