### ISSUE TITLE
Naming of AutoRaise

### ISSUE THREAD

**Issue by sbmpost** [synappser/AutoFocus#7]
Hi there. While I can't prevent people from making similar tools like the original [AutoRaise](https://github.com/sbmpost/AutoRaise), it would have been nice if at least the name was chosen differently. The tool I wrote has been around for over 5 years and is referenced from [stackoverflow](https://stackoverflow.com/questions/98310/focus-follows-mouse-plus-auto-raise-on-mac-os-x) as well, so it is kind of hard to miss it.

**Comment by synappser** [comment]
Hey Stefan, I'm sorry about the name clash.

I learned about your AutoRaise a couple of weeks ago through a Reddit comment to my announcement. As stated in my introduction, I took the name and inspiration of mine from the discontinued Zooom/2 [Auto Raise](https://img.informer.com/screenshots_mac/19/19146_1.png) feature of which I owned a copy.

Anyway, mine is still fresh and I can _afford_ a renaming without much inconvenience. I'll come up with something similar enough, maybe AutoFocus.

Thank you for the heads up and good luck with your own endeavours.
